name: pullrequest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Input check
    runs-on: ubuntu-latest
    steps:
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
