name: pullrequest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  update-verion:
    if:  github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: update version
        run: |
          echo done
        
