name: pullrequest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  FILE_WITH_VERSION: "Client/wwwroot/service-worker.published.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Harbor
        run: |
          docker login ${REGISTRY} -u '${{ secrets.USERNAME_HARBOR }}' -p '${{ secrets.PASSWORD_HARBOR }}'
      - name: Build
        run: |
          docker build -t ${REGISTRY}/${CONTAINER_PATH}:latest .
      - name: Push
        run: |
          docker push ${REGISTRY}/${CONTAINER_PATH}:latest
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update version
        run: |
          export version=$(cat $FILE_WITH_VERSION | grep -w  'cacheVersion = ' | awk '{print $4}' |  tr -d "';")
          export new_version=$(echo $(( version + 1 )))
          sed -i "s|$version|$new_version|g" $FILE_WITH_VERSION
          cat $FILE_WITH_VERSION
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.FILE_WITH_VERSION }}
