name: pullrequest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  update-verion:
    if:  github.event.pull_request.merged != false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update version
        run: |
          echo ${{ github.event.pull_request.merged }}
        

          
        
